import { useState } from "react";
import { Activity, BarChart3, BookOpen, Check, ChevronRight, Code2, FileUp, Lock, Play, ShieldAlert, Sparkles, Trophy, Users } from "lucide-react";

type Role = "student" | "admin";
type Route = "home" | "map" | "modes" | "understanding" | "quest" | "feedback" | "recovery" | "result" | "recall" | "mastery" | "error-dungeon" | "boss" | "live" | "ai-adversary" | "admin-dashboard" | "admin-upload" | "admin-generate" | "admin-world" | "admin-questions" | "admin-analytics" | "lab";

type Props = { route: Route; role: Role; navigate: (route: Route) => void; addXp: (value: number) => void; notify: (message: string) => void };
const concepts = ["LLM và Chatbot", "Next-token Prediction", "Tool Calling", "Prompt Engineering", "RAG", "AI Safety"];
const modes: Array<[Route, string, string, string]> = [
  ["quest", "Story Quest", "Học theo cốt truyện và checkpoint.", "⌘"],
  ["recall", "Daily Recall", "Ôn tập ngắt quãng theo trí nhớ.", "↻"],
  ["error-dungeon", "Error Dungeon", "Biến lỗi sai thành nhiệm vụ.", "⚑"],
  ["lab", "Lab Arena", "Áp dụng kiến thức bằng code.", "{ }"],
  ["boss", "Boss Battle", "Tổng hợp nhiều loại bằng chứng.", "♛"],
  ["live", "Live Class Battle", "Thi đấu trực tiếp cùng lớp.", "●"],
  ["ai-adversary", "AI Adversary", "Phát hiện claim thiếu căn cứ.", "◈"],
];
const PageHead = ({ eyebrow, title, text, action }: { eyebrow: string; title: string; text: string; action?: React.ReactNode }) => <div className="vs-head"><div><span>{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>{action}</div>;
const Metric = ({ label, value, note }: { label: string; value: string; note: string }) => <div className="vs-card vs-metric"><small>{label}</small><strong>{value}</strong><span>{note}</span></div>;
const Progress = ({ value }: { value: number }) => <div className="vs-progress"><i style={{ width: `${value}%` }} /></div>;

export function VisionScreen({ route, role, navigate, addXp, notify }: Props) {
  const [selected, setSelected] = useState<string | null>(null);
  const [text, setText] = useState("");
  const [done, setDone] = useState(false);
  if (route === "home") return <><PageHead eyebrow="Xin chào, Linh" title="Sẵn sàng tiếp tục hành trình?" text="Mỗi hoạt động tạo một loại bằng chứng học tập khác nhau." action={<button className="vs-primary" onClick={() => navigate("map")}>Tiếp tục khóa học</button>} /><div className="vs-grid four"><Metric label="Tổng XP" value="1.240" note="+105 hôm nay" /><Metric label="Chuỗi học" value="7 ngày" note="Kỷ lục: 12" /><Metric label="Khái niệm" value="2 / 8" note="5 đang tiến bộ" /><Metric label="Cần ôn" value="4" note="Khoảng 5 phút" /></div><div className="vs-layout"><section className="vs-card"><h2>Nhiệm vụ tiếp theo</h2><div className="vs-feature"><span>03</span><div><small>AI ODYSSEY · CHƯƠNG 3</small><h2>Giới hạn của LLM và Tool Calling</h2><p>Phân biệt phần xác suất và phần cần xử lý xác định.</p><Progress value={58} /></div><button onClick={() => navigate("quest")}>Bắt đầu <ChevronRight size={15} /></button></div></section><aside className="vs-card"><h3>Hoạt động gần đây</h3>{["Sửa hiểu lầm · Feature Scaling", "Ôn tập · MSE Loss", "Code application · Tool Calling"].map((x) => <div className="vs-list" key={x}><Check size={16} /><span>{x}</span></div>)}</aside></div></>;
  if (route === "map") return <><PageHead eyebrow="AI Odyssey" title="Bản đồ khóa học" text="Mỗi vùng mở khóa khi bạn tạo đủ bằng chứng học tập." /><div className="vs-map">{concepts.map((item, index) => <button className={index < 3 ? "open" : "locked"} key={item} onClick={() => index < 3 ? navigate("quest") : notify("Vùng này chưa được mở khóa.")}><span>{index < 3 ? index + 1 : <Lock size={18} />}</span><div><small>VÙNG {index + 1}</small><h3>{item}</h3><p>{index < 3 ? `${40 + index * 20}% hoàn thành` : "Hoàn thành vùng trước để mở"}</p></div></button>)}</div></>;
  if (route === "modes") return <><PageHead eyebrow="7 cách chứng minh bạn hiểu" title="Chế độ chơi" text="Chọn trải nghiệm phù hợp với loại bằng chứng bạn muốn luyện." /><div className="vs-grid three">{modes.map(([target, title, desc, icon]) => <article className="vs-card vs-mode" key={target}><i>{icon}</i><h2>{title}</h2><p>{desc}</p><button onClick={() => navigate(target)}>Vào chế độ <ChevronRight size={14} /></button></article>)}</div></>;
  if (route === "understanding") return <><PageHead eyebrow="Hackathon MVP" title="Hiểu Thật" text="Teach-back 1–2 câu để AI đối chiếu trực tiếp với transcript khóa học." /><div className="vs-layout"><section className="vs-card"><span className="vs-status">CHECKPOINT 1/3</span><h2>LLM khác chatbot như thế nào?</h2><p>Giải thích bằng lời của bạn trong 1–2 câu.</p><textarea value={text} onChange={(e) => setText(e.target.value)} placeholder="LLM là…, còn chatbot là…" /><button className="vs-primary" disabled={!text.trim()} onClick={() => { setDone(true); addXp(120); }}>Kiểm tra cách hiểu</button>{done && <div className="vs-success"><Check /> Đã hiểu · nguồn T04-046 · +120 XP</div>}</section><aside className="vs-card"><h3>Nguồn bài giảng</h3><blockquote>“Chatbot là một dạng giao diện; nền của nó được xây dựng dựa trên mô hình ngôn ngữ lớn.”</blockquote><span className="vs-status">T04-046 · VERIFIED</span></aside></div></>;
  if (route === "quest") return <><PageHead eyebrow="Story Quest · Chương 3" title="Đưa AI ra khỏi vùng đoán mò" text="Hoàn thành checkpoint để tiến qua câu chuyện." /><div className="vs-layout"><section className="vs-card"><div className="vs-story"><Sparkles /><div><small>TÌNH HUỐNG</small><h2>Người dùng hỏi số chữ R trong “strawberry”</h2><p>Thiết kế hệ thống nào đáng tin cậy hơn?</p></div></div>{["A · Yêu cầu LLM suy nghĩ kỹ hơn", "B · Gọi một function đếm ký tự", "C · Tăng temperature"].map((x) => <button className={`vs-answer ${selected === x ? "selected" : ""}`} onClick={() => setSelected(x)} key={x}>{x}</button>)}<button className="vs-primary" disabled={!selected} onClick={() => selected?.startsWith("B") ? navigate("result") : navigate("feedback")}>Nộp checkpoint</button></section><aside className="vs-card"><h3>Tiến trình vùng</h3><Progress value={60} /><p>3/5 checkpoint hoàn thành</p><div className="vs-list"><BookOpen />T03-034</div><div className="vs-list"><Code2 />Tool calling</div></aside></div></>;
  if (route === "feedback") return <><PageHead eyebrow="Phản hồi học tập" title="Chưa sửa được nguyên nhân gốc" text="Thử lại bằng một mô hình tư duy chắc chắn hơn." /><div className="vs-card vs-danger"><ShieldAlert size={34} /><h2>LLM vẫn là tác nhân xác suất</h2><p>Tăng temperature không biến phép đếm thành deterministic. Hãy chuyển tác vụ sang function code.</p><button onClick={() => navigate("recovery")}>Vào nhiệm vụ khắc phục</button></div></>;
  if (route === "recovery") return <><PageHead eyebrow="Recovery mission" title="Sửa hiểu lầm" text="Xem lại nguồn, giải thích lỗi và áp dụng vào ngữ cảnh mới." /><div className="vs-layout"><section className="vs-card"><span className="vs-status">BƯỚC 1/3</span><h2>Vì sao function code đáng tin cậy hơn?</h2><textarea value={text} onChange={(e) => setText(e.target.value)} placeholder="Vì function…" /><button className="vs-primary" disabled={text.length < 20} onClick={() => { addXp(25); navigate("result"); }}>Hoàn thành khắc phục</button></section><aside className="vs-card"><h3>T03-078</h3><p>Phần cần chắc chắn nên được tách khỏi mô hình xác suất và biểu diễn bằng công thức hoặc function code.</p></aside></div></>;
  if (route === "result") return <><PageHead eyebrow="Kết quả nhiệm vụ" title="Checkpoint hoàn thành" text="Bạn đã tạo thêm bằng chứng cho khái niệm Tool Calling." /><div className="vs-card vs-center"><Trophy size={46} /><h1>+80 XP</h1><p>Đã mở khóa Đấu trường thực hành</p><button className="vs-primary" onClick={() => navigate("lab")}>Vào Lab Arena</button></div></>;
  if (route === "recall") return <><PageHead eyebrow="Spaced practice" title="Ôn tập hằng ngày" text="Phiên ôn ngắn được tạo từ dự báo mức độ quên." /><div className="vs-layout"><section className="vs-card"><span className="vs-status">4 KHÁI NIỆM ĐẾN HẠN</span><h2>Tool Calling dùng để làm gì?</h2>{["Tăng độ sáng tạo", "Thực thi tác vụ xác định bên ngoài LLM", "Lưu lịch sử chat"].map((x) => <button className={`vs-answer ${selected === x ? "selected" : ""}`} onClick={() => setSelected(x)} key={x}>{x}</button>)}<button className="vs-primary" onClick={() => { setDone(true); addXp(35); }}>Kiểm tra</button>{done && <div className="vs-success">Đã làm mới lịch ôn · +35 XP</div>}</section><aside className="vs-card"><h3>Lịch tiếp theo</h3>{concepts.slice(0, 4).map((x, i) => <div className="vs-list" key={x}><span>{i + 1}</span><div><strong>{x}</strong><small>{i ? "3 ngày nữa" : "Ngày mai"}</small></div></div>)}</aside></div></>;
  if (route === "mastery") return <><PageHead eyebrow="Bằng chứng học tập" title="Mastery Dashboard" text="Mastery tăng từ recall, explanation, transfer và application." /><div className="vs-grid four"><Metric label="Tổng XP" value="1.345" note="+105 hôm nay" /><Metric label="Đã mastery" value="2 / 8" note="5 đang tiến bộ" /><Metric label="Khắc phục" value="78%" note="+12% tuần này" /><Metric label="Confidence match" value="84%" note="Hiệu chuẩn tốt" /></div><section className="vs-card vs-table"><h2>Năng lực theo khái niệm</h2>{concepts.map((x, i) => <div key={x}><strong>{x}</strong><Progress value={45 + i * 8} /><span>{2 + i} evidence</span><button onClick={() => navigate("recall")}>Luyện tập</button></div>)}</section></>;
  if (route === "error-dungeon") return <><PageHead eyebrow="Recovery zone" title="Hầm ngục sai lầm" text="Mỗi lỗi sai trong quá khứ trở thành một nhiệm vụ tập trung." /><div className="vs-grid three">{["LLM luôn đếm ký tự chính xác", "Loss thấp luôn tốt hơn", "Test data dùng để tuning"].map((x, i) => <article className={`vs-card ${i === 0 ? "vs-danger-card" : ""}`} key={x}><span className="vs-status">{i === 0 ? "ƯU TIÊN CAO" : "ĐANG CHỜ"}</span><h2>{x}</h2><p>Hiểu lầm khái niệm · cần tạo bằng chứng sửa sai.</p><button onClick={() => navigate("recovery")}>Bắt đầu khắc phục</button></article>)}</div></>;
  if (route === "boss") return <><PageHead eyebrow="Boss Battle" title="The Hallucination Hydra" text="Dùng nhiều loại bằng chứng để hạ từng lớp sai lệch." /><div className="vs-boss"><div><Trophy size={50} /><h1>HYDRA</h1><Progress value={68} /><small>HP 68%</small></div><section className="vs-card"><span className="vs-status">ĐÒN 1/5</span><h2>Khi nào nên chuyển tác vụ từ LLM sang tool?</h2>{["Khi cần output dài", "Khi tác vụ cần tính xác định", "Khi muốn temperature cao"].map((x) => <button className={`vs-answer ${selected === x ? "selected" : ""}`} onClick={() => setSelected(x)} key={x}>{x}</button>)}<button className="vs-primary" onClick={() => notify("Đòn đánh đã được ghi nhận.")}>Tấn công Boss</button></section></div></>;
  if (route === "live") return <><PageHead eyebrow="Phòng VINC-24" title="Live Class Battle" text={role === "admin" ? "Điều khiển trận đấu và theo dõi cách lớp suy luận." : "Cùng đội đưa ra quyết định và giải thích."} /><div className="vs-layout"><section className="vs-card"><div className="vs-live"><Users size={30} /><div><h2>Team Toolsmiths</h2><p>18/24 học viên đã tham gia</p></div><span>00:42</span></div><h2>Phần nào nên được triển khai bằng function code?</h2>{["Tóm tắt văn bản", "Đếm ký tự chính xác", "Viết slogan"].map((x) => <button className={`vs-answer ${selected === x ? "selected" : ""}`} onClick={() => setSelected(x)} key={x}>{x}</button>)}<button className="vs-primary" onClick={() => notify(role === "admin" ? "Đã khóa câu trả lời." : "Đã gửi câu trả lời cho đội.")}>{role === "admin" ? "Khóa đáp án" : "Gửi cho đội"}</button></section><aside className="vs-card"><h3>Bảng xếp hạng</h3>{["Toolsmiths · 820", "Prompt Rangers · 760", "RAG Raiders · 690"].map((x, i) => <div className="vs-list" key={x}><b>#{i + 1}</b>{x}</div>)}</aside></div></>;
  if (route === "ai-adversary") return <><PageHead eyebrow="Critical thinking" title="Đối thủ AI" text="Phát hiện claim thiếu căn cứ và buộc hệ thống quay về nguồn." /><div className="vs-layout"><section className="vs-card"><span className="vs-status">AI RESPONSE</span><h2>“LLM có thể thực thi trực tiếp mọi function được mô tả trong prompt.”</h2><p>Chọn đánh giá và giải thích bằng nguồn bài giảng.</p>{["Đúng", "Thiếu căn cứ / sai", "Không thể đánh giá"].map((x) => <button className={`vs-answer ${selected === x ? "selected" : ""}`} onClick={() => setSelected(x)} key={x}>{x}</button>)}<textarea value={text} onChange={(e) => setText(e.target.value)} placeholder="Giải thích vì sao…" /><button className="vs-primary" disabled={!selected || text.length < 20} onClick={() => { addXp(120); setDone(true); }}>Phản biện claim</button>{done && <div className="vs-success">Claim đã bị đánh dấu · +120 XP</div>}</section><aside className="vs-card"><h3>Nguồn có thể dùng</h3><p>T03-034 · Tool nhận input và trả output sau khi hệ thống thực thi.</p></aside></div></>;
  if (route === "admin-dashboard") return <><PageHead eyebrow="Course Studio" title="Chào buổi sáng, Dr. An" text="Theo dõi bằng chứng học tập và chuẩn bị can thiệp đúng lúc." action={<button className="vs-primary" onClick={() => navigate("admin-upload")}>Tạo khóa học mới</button>} /><div className="vs-grid four"><Metric label="Học viên hoạt động" value="126" note="+8 tuần này" /><Metric label="Mastery trung bình" value="64%" note="+5%" /><Metric label="Cần khắc phục" value="18" note="6 ưu tiên cao" /><Metric label="Question health" value="87%" note="21 verified" /></div><div className="vs-layout"><section className="vs-card"><h2>Tín hiệu cần chú ý</h2>{["Tool Calling · 38% hiểu sai", "RAG · 12 học viên cần ôn", "Prompt Injection · 6 case mới"].map((x) => <div className="vs-list" key={x}><Activity />{x}<button onClick={() => navigate("admin-analytics")}>Xem</button></div>)}</section><aside className="vs-card"><BarChart3 size={28} /><h2>Live Battle</h2><p>Phòng tiếp theo bắt đầu lúc 14:00.</p><button onClick={() => navigate("live")}>Mở phòng</button></aside></div></>;
  if (route === "admin-upload") return <><PageHead eyebrow="Course Studio" title="Tải bài giảng" text="VinCourse tạo world, checkpoint và recovery từ tài liệu thật." /><div className="vs-layout"><section className="vs-card vs-upload"><FileUp size={44} /><h2>Thả PDF vào đây</h2><p>PDF · tối đa 100 MB</p><button className="vs-primary" onClick={() => setDone(true)}>Chọn tệp demo</button>{done && <div className="vs-success">day03-tool-calling.pdf · sẵn sàng</div>}</section><aside className="vs-card"><h3>Cấu hình khóa học</h3><label>Tên khóa học<input value="AI Odyssey" readOnly /></label><label>Độ khó<select><option>Cơ bản đến trung cấp</option></select></label><button className="vs-primary" onClick={() => navigate("admin-generate")}>Tạo thế giới khóa học</button></aside></div></>;
  if (route === "admin-generate") return <><PageHead eyebrow="AI generation" title="Đang tạo thế giới khóa học" text="Trích concept, tạo checkpoint và nối từng câu với nguồn." /><div className="vs-card vs-center"><Sparkles size={48} /><h1>82%</h1><Progress value={82} /><p>Đang xây dựng recovery missions và Lab Arena…</p><button className="vs-primary" onClick={() => navigate("admin-world")}>Xem kết quả demo</button></div></>;
  if (route === "admin-world") return <><PageHead eyebrow="Generated course world" title="AI Odyssey" text="10 vùng · 50 checkpoint · 7 chế độ chơi" action={<button className="vs-primary" onClick={() => notify("Khóa học đã được xuất bản.")}>Xuất bản</button>} /><div className="vs-grid three">{concepts.map((x, i) => <article className="vs-card" key={x}><span className="vs-status">ZONE {i + 1}</span><h2>{x}</h2><p>{5 + i} checkpoint · {i % 2 ? "1 recovery" : "Lab Arena"}</p><Progress value={60 + i * 5} /><button onClick={() => navigate("admin-questions")}>Xem câu hỏi</button></article>)}</div></>;
  if (route === "admin-questions") return <><PageHead eyebrow="Question Studio" title="Review 24 câu hỏi" text="Duyệt độ rõ ràng, nguồn và misconception trước khi xuất bản." action={<button className="vs-primary" onClick={() => notify("Đã duyệt toàn bộ câu verified.")}>Duyệt verified</button>} /><section className="vs-card vs-table"><div className="vs-question-head"><strong>Câu hỏi</strong><strong>Nguồn</strong><strong>Trạng thái</strong><strong /></div>{["LLM và chatbot khác nhau thế nào?", "Khi nào cần tool calling?", "RAG giảm giới hạn nào?", "Prompt injection nguy hiểm ra sao?"].map((x, i) => <div className="vs-question-head" key={x}><span>{x}</span><span>T0{3 + i}-0{34 + i}</span><span className="vs-status">{i === 3 ? "CẦN REVIEW" : "VERIFIED"}</span><button onClick={() => notify("Câu hỏi đã được duyệt.")}>Duyệt</button></div>)}</section></>;
  if (route === "admin-analytics") return <><PageHead eyebrow="Learning analytics" title="Tín hiệu hiểu thật" text="Theo dõi mastery, misconception và recovery theo nguồn dữ liệu." /><div className="vs-grid four"><Metric label="Completion" value="76%" note="+9%" /><Metric label="Mastery" value="64%" note="+5%" /><Metric label="Recovery rate" value="78%" note="+12%" /><Metric label="Confidence match" value="84%" note="Ổn định" /></div><div className="vs-layout"><section className="vs-card"><h2>Mastery theo concept</h2>{concepts.map((x, i) => <div className="vs-analytics" key={x}><span>{x}</span><Progress value={48 + i * 7} /><strong>{48 + i * 7}%</strong></div>)}</section><aside className="vs-card"><h3>Top misconception</h3>{["LLM = chatbot · 32", "Tool tự chạy trong model · 24", "RAG loại bỏ hallucination · 18"].map((x, i) => <div className="vs-list" key={x}><b>{i + 1}</b>{x}</div>)}</aside></div></>;
  return <PageHead eyebrow="VinCourse" title="Màn hình đang được chuẩn bị" text="Route này đã có trong React shell." />;
}
